Add implementation for Czech language
goatshriek/stumpless pull request #194
Opened 2021-10-25 18:30 UTC by palike608

I hope my translation will be fine. :)

2021-10-25 21:26 UTC, goatshriek requested changes
These changes look good, thank you for putting them together! I have one minor comment on the translations below, which should be a simple change.

Also, please merge in the other pull requests you have opened to this single branch (`patch-1`) so that they can be bundled together into a single PR for testing. I'll close the others referencing this PR as the main one to merge to.

2021-10-25 21:26 UTC, goatshriek commented on include/private/config/locale/cz-cz.h
> +"FILE OPEN CHYBOVÉ HLÁŠENÍ"
For those that are in all capital letters, the ideal translation would be one of the phrase in the [English locale](https://github.com/goatshriek/stumpless/blob/latest/include/private/config/locale/en-us.h), instead of the string symbol itself.

These placeholders do exist in other translations for strings that were added after the initial translation, but since this is a new translation it would be ideal to use the more descriptive phrase instead of the symbol name.

2021-10-26 09:05 UTC, palike608 commented on include/private/config/locale/cz-cz.h
> +"FILE OPEN CHYBOVÉ HLÁŠENÍ"
Ok, i will add anothers edited files into this pull request and i will reedit phrase with all capital letters.

2021-10-26 10:25 UTC, goatshriek approved these changes

2021-10-26 10:29 UTC, goatshriek commented
Excellent work! Pending the passing of the tests (except for the code analysis one which will fail no matter what), I will merge these in when I have some time in the next 24 hours.

2021-10-26 20:24 UTC, merged

2021-10-26 21:43 UTC, palike608 commented
thank you for cooperation :)