Use fixed buffer for element names (#256)
goatshriek/stumpless pull request #258
Opened 2022-10-11 04:15 UTC by adsr

Per #256, for hacktoberfest

2022-10-11 12:43 UTC, goatshriek requested changes
Thank you for putting this together, it is mostly there! There are a few changes noted above for you to work on. Also, run the header check if you can before pushing your updates to try to avoid another static analysis failure.

2022-10-11 12:43 UTC, goatshriek commented on src/element.c
> +  snprintf( element->name, sizeof(element->name), "%s", name );
Refrain from using format-string based functions such as `snprintf` unless absolutely necessary. In this case, you can gather the length of the string first and then use a memcpy operation to move the string over.

2022-10-11 12:43 UTC, goatshriek commented on src/element.c
>  fail_mutex:
remove this label now that it is empty

2022-10-11 12:43 UTC, goatshriek commented on src/element.c
> -  free_mem( element );
the element will still need to be cleaned up in the event of a failure, so this error branch cannot be removed.

2022-10-11 12:43 UTC, goatshriek commented on src/element.c
> +  snprintf( element->name, sizeof(element->name), "%s", name );
Again, remove the use of `snprintf` here as well. Use the definition of `stumpless_set_entry_app_name` as a template for what to do here, as the `strlen` can be done outside of the critical section to improve performance.

2022-10-12 23:11 UTC, adsr reviewed
Thanks @goatshriek

2022-10-12 23:11 UTC, adsr commented on src/element.c
>  fail_mutex:
I left this label in because we need to free the element in this case as you mentioned in your comment below.

2022-10-12 23:11 UTC, adsr commented on src/element.c
> -  free_mem( element );
Ack

2022-10-13 01:04 UTC, goatshriek commented
Everything looks good to go, you just need to remove the include that is no longer needed as flagged by the header check.

It looks like the coverage dropped slightly because this change exposed some missing explicit tests for the copy element functionality. I'll create a follow up issue to deal with that separately.

2022-10-13 01:06 UTC, goatshriek requested changes
Remove the private/strhelper.h include from src/element.c to pass the header check.

2022-10-13 03:55 UTC, adsr commented
Thanks again @goatshriek. (I see now that you have to quote the glob path you pass to the check_headers script. I mistakenly assumed the intention was shell expansion.)

2022-10-13 08:32 UTC, goatshriek approved these changes

2022-10-13 08:32 UTC, merged