Set get for entry hostname
goatshriek/stumpless pull request #307
Opened 2022-11-08 23:29 UTC by Gustrb

This Pull Request is a response to the issue: #294
The hostname field is a 255 printable ASCII field in RFC 5424, and users may want to set this to something more meaningful to them. This task implements a pair of functions to set and retrieve the hostname of an entry, which is used if it is set during entry formatting.

Make sure that your pull request follows the guidelines specified in the
[Guidelines for Contributing](../docs/CONTRIBUTING.md).

2022-11-09 02:14 UTC, goatshriek requested changes
Just a few minor changes to make and this should be good to go. You'll need to add entries for your new functions to `src/windows/stumpless.def` to resolve the Windows build issues.

Also, check out the valgrind failure to see if there is a memory leak identified.

2022-11-09 02:14 UTC, goatshriek commented on include/stumpless/entry.h
> +const char *stumpless_get_entry_hostname( const struct stumpless_entry *entry );
add a line break after the type, to match the formatting of other declarations

2022-11-09 22:29 UTC, Gustrb commented on include/stumpless/entry.h
> +const char *stumpless_get_entry_hostname( const struct stumpless_entry *entry );
sure!

2022-11-09 22:59 UTC, goatshriek commented
Looks like there are still some memory leaks: you will need to free results provided by the get hostname function at a minimum, as this is freshly allocated each time. The valgrind output itself will give you feedback on where the problem is.

2022-11-09 23:01 UTC, Gustrb commented
how can I check the valgrind output locally??

2022-11-09 23:21 UTC, goatshriek commented
Assuming you have valgrind installed, you just need to run the test case with it once built. So, from the cmake build directory, something like `valgrind ./function-test-entry` should reproduce the error that the debug build shows.

2022-11-09 23:29 UTC, Gustrb commented
Hmmm, got it, thank you

2022-11-10 01:15 UTC, goatshriek approved these changes

2022-11-10 01:17 UTC, merged

2022-11-10 01:18 UTC, goatshriek commented
Thanks very much for putting this together, and responding to the changes quickly!

2022-11-10 01:33 UTC, Gustrb commented
I'm really glad to help!!