Severity from buffer
goatshriek/stumpless pull request #384
Opened 2023-10-16 14:41 UTC by kirubaspace

This fixes https://github.com/goatshriek/stumpless/issues/383 

Make sure that your pull request follows the guidelines specified in the
[Guidelines for Contributing](../docs/CONTRIBUTING.md).

2023-10-16 16:00 UTC, kirubaspace commented
@goatshriek Could  you please review when you get time

2023-10-16 16:00 UTC, goatshriek commented
There are merge conflicts that must be resolved before this will be reviewed. It looks like you will need to do a fresh pull from `latest`, as the functionality has changed a bit since this branch appears to have started.

2023-10-17 09:25 UTC, goatshriek requested changes
Please review the current `stumpless_get_severity_enum` functionality and tests - it has been expanded recently. You'll need to make sure these newer features are preserved.

Rather than simply copying the functionality directly, it will make more sense to move the functionality to your function, and have the previous function call your new `_from_buffer` one so that code is not duplicated.

2023-10-18 05:00 UTC, kirubaspace commented
> Please review the current `stumpless_get_severity_enum` functionality and tests - it has been expanded recently. You'll need to make sure these newer features are preserved.
> 
> Rather than simply copying the functionality directly, it will make more sense to move the functionality to your function, and have the previous function call your new `_from_buffer` one so that code is not duplicated.

Moved the functionality to new function and updated the unit test. Please let me know if this is fine or any changes required

2023-10-18 10:34 UTC, goatshriek requested changes
Thanks for putting this together and getting it updated so quickly! Just a few minor tweaks for you to make.

To resolve the Windows errors, you'll need to add your new function to `src/windows/stumpless.def`, which will expose the call to linkers.

2023-10-18 10:34 UTC, goatshriek commented on test/function/severity.cpp
> +    EXPECT_EQ( result, -1 );
There should also be an `EXPECT_ERROR_ID_EQ` check here to make sure that the error code is what is expected in this case. It looks like that's also missing in the test that you based this one on, so feel free to add it there as well.

2023-10-19 11:05 UTC, goatshriek approved these changes

2023-10-19 11:07 UTC, merged