Implement Telugu (te-IN) localization
goatshriek/stumpless pull request #407
Opened 2024-02-18 09:42 UTC by AryasCodeTreks

This fixes https://github.com/goatshriek/stumpless/issues/117
Have added localization for Indian language: Telugu

2024-02-18 18:30 UTC, goatshriek commented
Thanks very much for putting this together! Just a small adjustment needed to bring the line lengths under 80 characters, and then this should be ready to merge.

2024-02-19 00:07 UTC, goatshriek requested changes
Reduce line lengths to 80 characters or less.

2024-02-19 14:16 UTC, AryasCodeTreks reviewed
Please check now.

2024-02-20 01:07 UTC, goatshriek approved these changes

2024-02-20 12:01 UTC, merged