Adding Sinhala and Japanese localizations
goatshriek/stumpless pull request #408
Opened 2024-02-23 20:01 UTC by dylmcgold

This change resolves #283 and #301 by adding Sinhala and Japanese localizations.

2024-02-24 04:43 UTC, goatshriek requested changes
Thank you very much for putting together this update with not just one but _two_ new locales! I believe the only fix needed is to add the `L10N_NETWORK_CLOSED_ERROR_MESSAGE` definition to the `si-lk.h` header, which is causing the two test build failures.

2024-02-26 17:59 UTC, dylmcgold commented
I added the missing header, thanks for reviewing it. I didn't know how to review the issue myself, but now I see the error message with an undeclared header.

2024-02-27 00:07 UTC, goatshriek approved these changes

2024-02-27 00:26 UTC, merged

2024-02-27 00:27 UTC, goatshriek commented
Thanks once again for putting this together, and for responding quickly to the requested changes! It is greatly appreciated!