Unused function
goatshriek/stumpless pull request #453
Opened 2024-09-29 04:32 UTC by Brijeshthummar02

issue #446

2024-09-29 11:16 UTC, goatshriek requested changes
Add an entry for `tolower` in `tools/check_headers/c_standard_library.yml` to resolve the missing header error.

2024-11-01 07:40 UTC, Brijeshthummar02 commented
@goatshriek any furthur changes?

2024-11-02 01:24 UTC, goatshriek requested changes
It's been long enough for the CI logs to have aged off, so I can't review what the last failure was from. Please remove the unrelated changes from the PR and the tests will re-run on the updated pull.

2024-11-02 01:24 UTC, goatshriek commented on docs/benchmark.md
These changes seem to be related to a different change - please take them out of this branch so that they can be merged in separate commits.

2025-01-13 19:56 UTC, goatshriek commented
Checking in to see if you plan to continue work on this, per the project's [inactivity policy](https://github.com/goatshriek/stumpless/blob/latest/docs/CONTRIBUTING.md#you-still-there).

2025-04-08 00:16 UTC, goatshriek commented
Closing as stale.

2025-04-08 00:16 UTC, closed without merging