Fixes #450: Adds new function for generating a shorter form prival string.
goatshriek/stumpless pull request #457
Opened 2024-10-03 19:23 UTC by Jackb18b

Adds a new function for a condensed and logger-standard prival string.

2024-10-03 20:46 UTC, goatshriek requested changes
This is off to a good start! You'll need to add your new function to `src/windows/stumpless.def` for the Windows tests to pass.

Review the issue and make sure that you understand the format. This is different from the `stumpless_get_prival_string` format: the `STUMPLESS` prefixes aren't needed and the string should be in lowercase.

2024-10-03 20:46 UTC, goatshriek commented on src/prival.c
> +  memcpy( priority_string + len_severity, ".", 1);
this can just be an assignment `priority_string[len_severity] = '.';` rather than a memcpy

2024-10-03 20:46 UTC, goatshriek commented on src/prival.c
> +  memcpy( priority_string + len_severity + 1 + len_facility, "\0", 1);
this can be a simple assignment as well

2024-10-03 20:46 UTC, goatshriek commented on test/function/prival.cpp
> +    EXPECT_STREQ( result, "STUMPLESS_SEVERITY_ERR.STUMPLESS_FACILITY_USER" );
refer to the issue for the correct format this string should have. In this case, it should be `user.err`.

2024-11-06 09:52 UTC, m3g4d1v3r commented
Hello @Jackb18b  and @goatshriek.
Can I co-author this PR? If you don't mind, I can make some commits after the old ones in order to let the PR pass the tests.

2024-11-07 00:51 UTC, goatshriek commented
With no response from the original author, I think you're safe to bring it across the finish line. Abandoned PRs are not uncommon, particularly around Hacktoberfest.

2024-11-07 18:47 UTC, m3g4d1v3r commented
I've added the fixes on another PR (#476) due to privilege issues on the original fork.

2024-11-09 17:09 UTC, goatshriek commented
This work was finished by #476. The original author here has been given co-author credit, as the work was based on this one.

2024-11-09 17:09 UTC, closed without merging