Adding an `alloc_array` function
goatshriek/stumpless pull request #458
Opened 2024-10-05 19:51 UTC by aadit-n3rdy

This PR solves #440 and adds an `alloc_array` function. All uses of `alloc_mem` which can be replaced with `alloc_array` have been replaced with `alloc_array`. A test for `stumpless_copy_entry` has been added as well.

2024-10-05 22:09 UTC, aadit-n3rdy commented
Both the failed tests were in calls to `alloc_mem`, is this a problem with `alloc_array`? I'll look into this as well.

2024-10-06 10:59 UTC, goatshriek requested changes
Excellent work! Just a few cleanup items: make sure that you aren't using tabs anywhere, and move the large struct into the new test instead of making it a fixture structure.

2024-10-06 10:59 UTC, goatshriek commented on src/memory.c
> +	return NULL;
it looks like there are some tabs here; please convert them to spaces

2024-10-06 10:59 UTC, goatshriek commented on test/function/entry.cpp
> +	  EXPECT_ERROR_ID_EQ( STUMPLESS_MEMORY_ALLOCATION_FAILURE );
looks like there are some tabs here as well

2024-10-06 10:59 UTC, goatshriek commented on test/function/entry.cpp
please move the creation/deletion of the `large_struct` out of the test fixture and into the single new test you've made, changing it from `TEST_F` to `TEST` in the process.

The structures in the fixture are intended to be valid, and since this one is a bit strange we only need to create it for this one specialized test.

2024-10-06 15:38 UTC, aadit-n3rdy commented on test/function/entry.cpp
Done, I've moved it to a separate test named `CopyEntry, MallocFailureOnSizeOverflow`. Does that work?

2024-10-06 23:53 UTC, goatshriek approved these changes

2024-10-06 23:56 UTC, merged