updated benchmark documentation to match code
goatshriek/stumpless pull request #467
Opened 2024-10-16 16:28 UTC by Brijeshthummar02

issue #444

2024-10-17 16:41 UTC, Brijeshthummar02 commented
@goatshriek need review.

2024-10-17 20:53 UTC, goatshriek requested changes
Please review the actual test in `test/performance/element.cpp`. The changes you have made here do not make the documentation match it.

2025-01-13 19:57 UTC, goatshriek commented
Checking in to see if you plan to continue work on this PR as well as your other, per the project's [inactivity policy](https://github.com/goatshriek/stumpless/blob/latest/docs/CONTRIBUTING.md#you-still-there).

2025-01-14 15:51 UTC, Brijeshthummar02 commented
U can pass it to someone else.

2025-02-02 02:40 UTC, closed without merging