456-fix-error-codes
goatshriek/stumpless pull request #475
Opened 2024-11-03 19:32 UTC by Ankaa19

add errors to facility functions #456 

Error handling code was created for the following functions:
- stumpless_get_facility_string
- stumpless_get_facility_enum
- stumpless_get_facility_enum_from_buffer

2024-11-04 01:02 UTC, goatshriek requested changes
It's unclear to me why you've chosen to implement a file-specific error code instead of using the error code functionality already present in the library.

Please rework this change to use the library's existing error code functions (defined in `src/error.c` and used extensively throughout the project).

2024-11-04 01:02 UTC, goatshriek commented on include/private/.idea/.gitignore
The `.idea` folder should not be included in commits. It would make the most sense to add a line to the project `.gitignore` file that ignores folders with this name.

2024-11-07 19:17 UTC, Ankaa19 commented
hello, I change my pull request according to your comment. Is it ok?

2024-11-07 21:19 UTC, goatshriek commented
Please remove the `.idea` folder from the commits, and add tests as described in the original issue.

2024-11-21 19:41 UTC, Ankaa19 commented
Hello, 
sorry for delay. I was sick. I added tests according to the requirements in the issue to the pull request.
Please check it and if it's ok could you merge it?

2024-11-23 11:57 UTC, goatshriek commented
You'll need to get the tests passing, of course. From the one that I looked at you'll probably need to do a few rounds of tweaks and rebuilds.

2024-11-25 00:05 UTC, Ankaa19 commented
Sorry, this is my first time working with tests. I edit them and all tests passed. Is it ok this way?

2024-11-28 00:00 UTC, Ankaa19 commented
I'm sorry for inconvenience, in the previous edit here on github, not all the edits I have made have been changed. Can you please run the control again? I edited it now.

2024-11-30 18:05 UTC, goatshriek requested changes
Please see the first round of requested changes below, in addition to correcting the header check in the static analysis run that failed.

2024-11-30 18:05 UTC, goatshriek commented on .gitignore
> +include/private/.idea/
This should be made more general to ignore anything in a `.idea` folder, similar to the vscode folder already in the gitignore.

2024-11-30 18:05 UTC, goatshriek commented on src/facility.c
> +    if (!facility_string) {
use `VALIDATE_ARG_NOT_NULL_INT_RETURN` for this instead.

2024-11-30 18:05 UTC, goatshriek commented on src/facility.c
> +    if (!facility_buffer) {
use `VALIDATE_ARG_NOT_NULL_INT_RETURN` here as well

2024-11-30 18:05 UTC, goatshriek commented on test/function/facility.cpp
> +/*
don't comment out code -  in this case the old test should be able to remain, as it should continue to pass.

2024-11-30 18:05 UTC, goatshriek commented on test/function/facility.cpp
> +TEST(GetFacilityString, InvalidFacility) {
For all of these tests, use `EXPECT_ERROR_ID_EQ` to also check that the error code is appropriate. You can find examples of this in most of the other test suites.

2024-12-04 23:20 UTC, Ankaa19 commented
Requested changes have been done.

2024-12-08 13:16 UTC, Ankaa19 commented
I dont understant it. I set expect true but in errors is that it expect false. How it is possible? 
I see that you assigned pull request on you so I shouldn't continue with it?

2024-12-08 20:39 UTC, goatshriek commented
> I see that you assigned pull request on you so I shouldn't continue with it?

No, it's assigned so that you know who is reviewing it and responsible for giving you feedback when needed.

I haven't run the tests myself - are they passing when you run them locally? Have you tried adding some print statements or running the test using a debugger (e.g. `gdb ./function-test-facility` from the build directory) with breakpoints to understand the execution flow?

2025-01-13 19:58 UTC, goatshriek commented
Just checking in to see if you plan to continue work on this, per the project's [inactivity policy](https://github.com/goatshriek/stumpless/blob/latest/docs/CONTRIBUTING.md#you-still-there).

2025-01-13 20:08 UTC, Ankaa19 commented
Hello, sorry for inactivity. I can't finish it so I won't continue working on it. Sorry.

2025-01-13 20:17 UTC, goatshriek commented
No worries at all, hopefully this was a worthwhile learning experience for you!

2025-03-05 21:50 UTC, closed without merging